name: Build

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash
jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller --onefile --name=ForceTubeWS main.py

      - uses: Shopify/upload-to-release@v2.0.0
        with:
          name: ForceTubeWS.exe
          path: dist/ForceTubeWS.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
